# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a470027c4195cb1860e590cf4170a65d8cb777e4375f6ff0928f96b205529d3b94b460836366f1f330e9f3efea35a5d9785177fc1a9fd4514786a572db97111

test:
  secret_key_base: 266b78331fe4377fcd4b62b2ed7c3687b9902839e81385af4ccf835679c1c60ffc1eee3c213f8fbdd5c40fa4a821569191c4083d3f0285158d876e9e21372ac6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
